#- Cache directory, this is where the plugins will be downloaded
#- Plugin jars can also be dropped here and the program will use these jars to update
#- the servers
cachePath: "cache"

#- List of servers
servers:
  #- name: pluginsPath
  server1: "../../path/to/plugins"
  server2: "/path/to/plugins"

#- Map of plugins, each entry name must match the plugin name exactly as in `plugin.yml` of that plugin
plugins:
  name:
    #- Source type (github, gitlab, spigot)
    type: "github"
    #- Source Value. Depends on the type of source
    #- For `github` and `gitlab` this should be of form "owner/repository"
    #- For `spigot` ....
    value: "Owner/Repository"
    #- Access token that should be passed if the source is a private repository, if any.
    #- Leave it empty if you don't know what this is.
    auth: ""
